Auth/urls.py
from django.urls import path
from .views import Login, Logout, create_user, Users, UsersUpdate, ChangePassword

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='Login'),
    path('logout/', Logout.as_view(), name='Logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),

]

Core/urls.py
from django.urls import path 
from .views import Index

app_name = 'Core'
urlpatterns = [
    path('', Index.as_view(), name="Index")
]

ONSite/urls.py
from django.urls import path
from .views import  CreateHotIssue,CreateFullIssue, print_issue, IssueUpdate, FilesUpdate, DeleteFiles, FilesUpdateDive, AssignIssue, IssueDetails, FollwerAssign

app_name = 'ONSite'
urlpatterns = [
    # path('myIssue/', MyIssue.as_view(), name="MyIssue"),
    path('createHotIssue/', CreateHotIssue.as_view(), name="CreateHotIssue"),
    path('createFullIssue/', CreateFullIssue.as_view(), name="CreateFullIssue"),
    path('update_issue/<int:pk>/', IssueUpdate.as_view(), name='IssueUpdate'),
    path('files_update/<int:pk>/', FilesUpdate.as_view(), name='FilesUpdate'),
    path('delete_files/', DeleteFiles, name='DeleteFiles'),
    path('div_files/<int:pk>/', FilesUpdateDive.as_view(), name='FilesUpdateDive'),
    path('assign_issue/<int:pk>/', AssignIssue.as_view(), name='AssignIssue'),
    path('assign_follwer/<int:pk>/', FollwerAssign.as_view(), name='FollwerAssign'),
    path('issue_details/<int:pk>/', IssueDetails.as_view(), name='IssueDetails'),
    path('issue_print/<int:pk>/', print_issue, name='PrintIssue')
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('Core.urls')),
    path('onsite/', include('ONSite.urls')),
    path('api/', include('Tom.api.urls')),
    path('comment/', include('comment.urls')),
    path('',include('Auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from AdminMedule.models import *
from django.db import models
from Auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from django.urls import reverse


# Tom Module
class Device(models.Model):
    station_name = models.CharField(max_length=50, verbose_name="Station Name", null=True, blank=True)
    office_name = models.CharField(max_length=50, verbose_name="Office Name", null=True, blank=True)
    serial_number = models.CharField(max_length=50, verbose_name="Serial Number", null=True, blank=True)

    def __str__(self):
        return self.serial_number





GANDER = (
    (0, "Male"),
    (1, "Female")
)

# Enr Users Module
class EnrUser(models.Model):
    user_name = models.CharField(max_length=50, verbose_name="Username")
    password = models.CharField(max_length=50, verbose_name="Password")
    last_name = models.CharField(max_length=50, verbose_name="Last Name")
    first_name = models.CharField(max_length=50, verbose_name="First Name", null=True, blank=True)
    patronymic_name = models.CharField(max_length=50, verbose_name="Patronymic Name", null=True, blank=True)
    phone = models.CharField(max_length=50, verbose_name="Phone", null=True, blank=True)
    gander = models.IntegerField(choices=GANDER, verbose_name="Gander", null=True, blank=True)
    active = models.BooleanField(verbose_name="Active", null=True, blank=True)
    groups = models.TextField(verbose_name="Groups", null=True, blank=True)
    merchant_login = models.CharField(max_length=200, verbose_name="Marchent", null=True, blank=True)
    user = models.CharField(max_length=100, verbose_name="User", null=True, blank=True)

    def __str__(self):
        return self.user_name


# Issue Module
class Issue(models.Model):
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, verbose_name="Environment", null=True, blank=True)
    issue_class = models.ForeignKey(IssueClass, on_delete=models.CASCADE, verbose_name="Issue Class", null=True, blank=True)
    issue_type = models.ForeignKey(IssueType, on_delete=models.CASCADE, verbose_name="Issue Type", null=True,blank=True)
    priority = models.ForeignKey(Priroty, on_delete=models.CASCADE, verbose_name="Priority", null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name="Status", null=True, blank=True)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Reporter", null=True, blank=True)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, verbose_name = "Channel")
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name="Module")
    device_serial = models.ForeignKey(Device, on_delete=models.CASCADE, null=True, blank=True,verbose_name="Device Serial")

    description = models.TextField(verbose_name="Description")
    title = models.CharField(max_length=200, verbose_name="Title")
    jira_id = models.CharField(max_length=20, verbose_name="Jira Id", null=True, blank=True)
    assignee = models.ForeignKey(User, related_name="issue_assignee", on_delete=models.CASCADE, verbose_name= "assignee", null=True, blank=True)
    actor = models.ForeignKey(User, related_name="issue_actor", on_delete=models.CASCADE, verbose_name= "actor", null=True, blank=True)

    create_date= models.DateTimeField(verbose_name="Create Date", null=True, blank=True)
    update_date = models.DateTimeField(verbose_name="Last Update", null=True, blank=True)

    affects_version = models.FloatField(verbose_name="Affects Version", null=True, blank=True)
    fix_version = models.FloatField(verbose_name="Fix Version", null=True, blank=True)

    train_number = models.CharField(max_length=20, null=True, blank=True,  verbose_name="Train Number")
    train_from = models.CharField(max_length=20,  null=True, blank=True, verbose_name="Train From")
    train_to = models.CharField(max_length=20,  null=True, blank=True, verbose_name="Train To")
    trip_date = models.DateField(verbose_name="Trip Date", null=True, blank=True)

    teller = models.ForeignKey(EnrUser, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Teller")
    station = models.ForeignKey(Station, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Station")
    comments = GenericRelation(Comment)

    subscription_type = models.CharField(max_length=50, null=True, blank=True, verbose_name="Subscription Type")
    subscription_number = models.IntegerField(null=True, blank=True, verbose_name="Subscription Number")
    subscription_expiry_date = models.DateField(null=True, blank=True, verbose_name="Subscription Expiry Date")

    teller_name = models.CharField(max_length=50, null=True, blank=True, verbose_name="Teller Name")
    teller_phone = models.CharField(max_length=15, null=True, blank=True, verbose_name="Teller phone")

    trans_number = models.CharField(max_length=10, null=True, blank=True, verbose_name="M#")


    def get_absolute_url(self):
        return reverse('ONSite:IssueUpdate', kwargs={'pk': self.id})
    

Core/forms.py
from django import forms

Core/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import  get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Issue, Status
from django_user_agents.utils import get_user_agent
from django.views.generic import ListView, UpdateView, CreateView, DetailView
from .models import Status, Module
from Auth.models import User
# Create your views here.


class Index(LoginRequiredMixin, ListView):
    login_url = '/auth/login'
    model = Issue
    paginate = 50
    template_name = 'Core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = Status.objects.all()
        context['module'] = Module.objects.all()
        return context


    def get_queryset(self):
        queryset = self.model.objects.filter(reporter=self.request.user).order_by('-id') | self.model.objects.filter(assignee=self.request.user).order_by('-id')
        if self.request.GET.get('issue_number'):
            queryset= self.model.objects.filter(id=self.request.GET.get('issue_number')).order_by('-id')
        if self.request.GET.get('title'):
            queryset= self.model.objects.filter(title__icontains=self.request.GET.get('title')).order_by('-id')
        if self.request.GET.get('date_from'):
            queryset = self.model.objects.filter(create_date__gte=self.request.GET.get('date_from')).order_by('-id')
        if self.request.GET.get('date_to'):
            queryset = self.model.objects.filter(create_date__lte=self.request.GET.get('date_to')).order_by('-id')
        if self.request.GET.get('module'):
            queryset = self.model.objects.filter(module__in=self.request.GET.get('module'))
        if self.request.GET.get('status'):
            queryset = self.model.objects.filter(status_id__in=self.request.GET.get('status'))


        def issue_weight():
            user_list = []
            queryset = User.objects.all()
            for i in queryset:
                user_list.append(i)

            print(user_list)
        issue_weight()
        return queryset

Core/templates/core/filter.html
<div class="collapse" id="filter_div">
    <div class="card">
        <div class="card-header bg-dark">
           <span class="font-size-20pt text-light"><i class="fas fa-filter"></i> Filter</span>
        </div>
         <form method="get" action="#"  style="height: 80%">
              <div class="card-body">
                    <div class="row">
                        <div class="col-lg-4 col-sm-12">
                            <div class="form-group" >
                                <label for="issue_number">Issue Number</label>
                                <input type="number"  id="issue_number" name="issue_number"  placeholder="Type here...." class="form-control border border-primary"/>
                            </div>
                        </div>
                        <div class="col-lg-6 col-sm-12">
                            <div class="form-group">
                                <label for="title">title</label>
                                <input id="title" name="title"  placeholder="Type here...."  class="form-control border border-primary" />
                             </div>
                        </div>

                         <div class="col-lg-2 col-sm-12">
                            <div class="form-group">
                            <label for="issue_number">Status</label>
                                <select id="status" name="status" data-toggle="select" multiple class="form-control border border-primary">
                                    {% if status %}
                                        {% for x in status %}
                                        <option value={{ x.id }}>{{ x.name }}</option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>

                        <div class="col-lg-6 col-sm-12">
                             <div class="form-group">
                                <label for="module">Module</label>
                                <select id="module" name="module" data-toggle="select" multiple class="form-control border border-primary">
                                    {% if module %}
                                        {% for i in module %}
                                         <option value={{ i.id }}>{{ i.name }}</option>
                                        {% endfor %}
                                    {% endif %}
                                </select>
                            </div>
                        </div>

                         <div class="col-lg-3 col-sm-12">
                            <div class="form-group">
                                 <label for="issue_number">Date From</label>
                                <input type="date" id="date_from" name="date_from" placeholder="Type here...." class="form-control border border-primary"/>
                            </div>
                        </div>

                        <div class="col-lg-3 col-sm-12">
                            <div class="form-group">
                                 <label for="date_to">Date To</label>
                                <input type="date" id="date_to"  name="date_to" placeholder="Type here...." class="form-control border border-primary"/>
                            </div>
                        </div>

                    </div>

                  </div>

                 <div class="card-footer">
                      <button  class="btn btn-info btn-block-xs">
                            <span> Search </span>
                      </button>
                </div>

         </form>

    </div>

</div>

Core/templates/core/header.html
<!-- Header -->
<div class="navbar navbar-expand navbar-shadow px-0  pl-lg-16pt navbar-light bg-body"
     id="default-navbar"
     data-primary>

    <!-- Navbar toggler -->
    <button class="navbar-toggler d-block d-lg-none rounded-0"
            type="button"
            data-toggle="sidebar">
        <span class="material-icons">menu</span>
    </button>

{#    <!-- Navbar Brand -->#}
{#    <a href="{% url 'Core:Index' %}"#}
{#       class="navbar-brand mr-16pt d-lg-none">#}
{#        <img class="navbar-brand-icon mr-0 mr-lg-8pt"#}
{#             src="/static/assets/images/ecards2.png"#}
{#             width="32"#}
{#             alt="Huma">#}
{#        <span class="d-none d-lg-block">E-support</span>#}
{#    </a>#}

 <div class="flex-nowrap">
     <div class="nav-item ml-16pt ">
        <a class="btn btn-outline-info " style="width: 100%"  href="{% url 'Core:Index' %}"  >
            <span><i class="fas fa-list"></i> </span>
        </a>
     </div>

 </div>

 <div class="nav-item ml-16pt">
        <a class="btn btn-outline-info "  data-toggle="collapse" data-target="#filter_div">
           <span><i class="fas fa-filter"></i></span>
        </a>

</div>

 <div class="nav-item ml-16pt">
        <a class="btn btn-outline-info "  href="{% url 'ONSite:CreateFullIssue' %}" data-toggle="modal" data-target="#sub_modal">
           <span><i class="fas fa-star"></i></span>
        </a>
</div>


<div class="flex">
     <div class="nav-item ml-16pt">
            <a class="btn btn-outline-info "  href="{% url 'ONSite:CreateHotIssue' %}" data-toggle="modal" data-target="#sub_modal">
               <span><i class="fas fa-fire"></i></span>
            </a>
    </div>

</div>

    <div class="nav navbar-nav flex-nowrap d-flex ml-0 mr-16pt">
        <!-- Notifications dropdown -->
        <div class="nav-item mr-auto dropdown dropdown-notifications">
            <button class="nav-link btn-flush dropdown-toggle"
                    type="button"
                    data-toggle="dropdown"
                    data-dropdown-disable-document-scroll
                    data-caret="false">
                <i class="material-icons">notifications</i>
                <span class="badge badge-notifications badge-accent">2</span>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <div data-perfect-scrollbar
                     class="position-relative">
                    <div class="dropdown-header"><strong>System notifications</strong></div>
                    <div class="list-group list-group-flush mb-0">

                        <a href="javascript:void(0);"
                           class="list-group-item list-group-item-action unread">
                            <span class="d-flex align-items-center mb-1">
                                <small class="text-black-50">3 minutes ago</small>

                                <span class="ml-auto unread-indicator bg-accent"></span>

                            </span>
                            <span class="d-flex">
                                <span class="avatar avatar-xs mr-2">
                                    <span class="avatar-title rounded-circle bg-light">
                                        <i class="material-icons font-size-16pt text-accent">account_circle</i>
                                    </span>
                                </span>
                                <span class="flex d-flex flex-column">

                                    <span class="text-black-70">Your profile information has not been synced correctly.</span>
                                </span>
                            </span>
                        </a>

                    </div>
                </div>
            </div>
        </div>
        <!-- // END Notifications dropdown -->


        <div class="nav-item dropdown d-none d-sm-flex">
            <a href="#"
               class="nav-link d-flex align-items-center dropdown-toggle"
               data-toggle="dropdown">
                <img width="32"
                     height="32"
                     class="rounded-circle mr-8pt"
                     src="
                        {% if request.user.avater %}
                            {{ request.user.avater.url }}
                        {% else %}
                            /static/assets/images/logo.png
                        {% endif %}
                        "
                     alt="account" />
                <span class="flex d-flex flex-column mr-8pt">
                    <span class="navbar-text-100">{{ request.user.username }}</span>
                    <small class="navbar-text-50">Admin</small>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
{#                <div class="dropdown-header"><strong>Account</strong></div>#}
{#                <a class="dropdown-item"#}
{#                   href="edit-account.html">Edit Account</a>#}
                <a class="dropdown-item"
                   href="{% url 'Auth:Logout' %}">Logout</a>
            </div>
        </div>

    </div>

</div>
<!-- // END Header -->

Core/templates/core/index.html
{% extends "base2.html" %}

{% block issue_div %}
<div class=" mb-24pt" id="issue_list">
    {% include 'on_site_issue_div.html' %}
</div>
{% endblock %}

Core/templates/core/sidebar.html
 <!-- drawer -->
            <div class="mdk-drawer js-mdk-drawer"
                 id="default-drawer">
                <div class="mdk-drawer__content">
                    <div class="sidebar sidebar-dark sidebar-left"
                         data-perfect-scrollbar>

                        <a href="index.html" class="sidebar-brand ">
                           <img src="/static/assets/images/ecards2.png" width="200px">
                        </a>
                        <form action="index.html"
                              class="search-form flex-shrink-0 search-form--black sidebar-m-b sidebar-p-l mx-16pt pr-0">
                            <input type="text"
                                   class="form-control pl-0"
                                   placeholder="Search">
                            <button class="btn"
                                    type="submit"><i class="material-icons">search</i></button>
                        </form>

                        <div class="sidebar-heading">Issue</div>
                        <ul class="sidebar-menu">
                            <li class="sidebar-menu-item">
                                <a class="sidebar-menu-button js-sidebar-collapse"
                                   data-toggle="collapse"
                                   href="#enterprise_menu">
                                    <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left"><i class="fas fa-list-alt"></i></span>
                                    My Issue
                                    <span class="ml-auto sidebar-menu-toggle-icon"></span>
                                </a>
                                <ul class="sidebar-submenu collapse sm-indent"
                                    id="enterprise_menu">
                                    <li class="sidebar-menu-item">
                                        <a class="sidebar-menu-button"
                                           href="{% url 'ONSite:CreateHotIssue' %}" data-toggle="modal" data-target="#sub_modal">
                                            <span class="sidebar-menu-text">Add New</span>
                                        </a>
                                    </li>
                                    <li class="sidebar-menu-item">
                                        <a class="sidebar-menu-button"
                                           href="{% url 'Core:Index' %}">
                                            <span class="sidebar-menu-text">List</span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
{#                            <li class="sidebar-menu-item">#}
{#                                <a class="sidebar-menu-button"#}
{#                                   data-toggle="collapse"#}
{#                                   href="#productivity_menu">#}
{#                                    <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left"><i class="fas fa-train"></i></span>#}
{#                                    Stations#}
{#                                    <span class="ml-auto sidebar-menu-toggle-icon"></span>#}
{#                                </a>#}
{#                                <ul class="sidebar-submenu collapse sm-indent"#}
{#                                    id="productivity_menu">#}
{#                                    <li class="sidebar-menu-item">#}
{#                                        <a class="sidebar-menu-button"#}
{#                                           href="projects.html">#}
{#                                            <span class="sidebar-menu-text">Add New</span>#}
{#                                        </a>#}
{#                                    </li>#}
{#                                    <li class="sidebar-menu-item">#}
{#                                        <a class="sidebar-menu-button"#}
{#                                           href="tasks-board.html">#}
{#                                            <span class="sidebar-menu-text">List</span>#}
{#                                        </a>#}
{#                                    </li>#}
{##}
{##}
{#                                </ul>#}
{#                            </li>#}
                        </ul>

                    </div>
                </div>
            </div>
            <!-- // END drawer -->