Auth/urls.py
from django.urls import path
from .views import Login, Logout, create_user, Users, UsersUpdate, ChangePassword

app_name = "Auth"
urlpatterns = [
    path('users/login/', Login.as_view(), name='Login'),
    path('logout/', Logout.as_view(), name='Logout'),
    path('ChangePassword/', ChangePassword, name='ChangePassword'),
    path('AddNewUser/', create_user, name='create_user'),
    path('Users/', Users.as_view(), name='Users'),
    path('Users/<int:pk>/update/', UsersUpdate.as_view(), name='UsersUpdate'),

]

Core/urls.py
from django.urls import path 
from .views import Index

app_name = 'Core'
urlpatterns = [
    path('', Index.as_view(), name="Index")
]

ONSite/urls.py
from django.urls import path
from .views import  CreateHotIssue,CreateFullIssue, print_issue, IssueUpdate, FilesUpdate, DeleteFiles, FilesUpdateDive, AssignIssue, IssueDetails, FollwerAssign

app_name = 'ONSite'
urlpatterns = [
    # path('myIssue/', MyIssue.as_view(), name="MyIssue"),
    path('createHotIssue/', CreateHotIssue.as_view(), name="CreateHotIssue"),
    path('createFullIssue/', CreateFullIssue.as_view(), name="CreateFullIssue"),
    path('update_issue/<int:pk>/', IssueUpdate.as_view(), name='IssueUpdate'),
    path('files_update/<int:pk>/', FilesUpdate.as_view(), name='FilesUpdate'),
    path('delete_files/', DeleteFiles, name='DeleteFiles'),
    path('div_files/<int:pk>/', FilesUpdateDive.as_view(), name='FilesUpdateDive'),
    path('assign_issue/<int:pk>/', AssignIssue.as_view(), name='AssignIssue'),
    path('assign_follwer/<int:pk>/', FollwerAssign.as_view(), name='FollwerAssign'),
    path('issue_details/<int:pk>/', IssueDetails.as_view(), name='IssueDetails'),
    path('issue_print/<int:pk>/', print_issue, name='PrintIssue')
]

ZerOne/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls.conf import include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('Core.urls')),
    path('onsite/', include('ONSite.urls')),
    path('api/', include('Tom.api.urls')),
    path('comment/', include('comment.urls')),
    path('',include('Auth.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    url(r'^select2/', include('django_select2.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from AdminMedule.models import *
from django.db import models
from Auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from comment.models import Comment
from django.urls import reverse


# Tom Module
class Device(models.Model):
    station_name = models.CharField(max_length=50, verbose_name="Station Name", null=True, blank=True)
    office_name = models.CharField(max_length=50, verbose_name="Office Name", null=True, blank=True)
    serial_number = models.CharField(max_length=50, verbose_name="Serial Number", null=True, blank=True)

    def __str__(self):
        return self.serial_number





GANDER = (
    (0, "Male"),
    (1, "Female")
)

# Enr Users Module
class EnrUser(models.Model):
    user_name = models.CharField(max_length=50, verbose_name="Username")
    password = models.CharField(max_length=50, verbose_name="Password")
    last_name = models.CharField(max_length=50, verbose_name="Last Name")
    first_name = models.CharField(max_length=50, verbose_name="First Name", null=True, blank=True)
    patronymic_name = models.CharField(max_length=50, verbose_name="Patronymic Name", null=True, blank=True)
    phone = models.CharField(max_length=50, verbose_name="Phone", null=True, blank=True)
    gander = models.IntegerField(choices=GANDER, verbose_name="Gander", null=True, blank=True)
    active = models.BooleanField(verbose_name="Active", null=True, blank=True)
    groups = models.TextField(verbose_name="Groups", null=True, blank=True)
    merchant_login = models.CharField(max_length=200, verbose_name="Marchent", null=True, blank=True)
    user = models.CharField(max_length=100, verbose_name="User", null=True, blank=True)

    def __str__(self):
        return self.user_name


# Issue Module
class Issue(models.Model):
    environment = models.ForeignKey(Environment, on_delete=models.CASCADE, verbose_name="Environment", null=True, blank=True)
    issue_class = models.ForeignKey(IssueClass, on_delete=models.CASCADE, verbose_name="Issue Class", null=True, blank=True)
    issue_type = models.ForeignKey(IssueType, on_delete=models.CASCADE, verbose_name="Issue Type", null=True,blank=True)
    priority = models.ForeignKey(Priroty, on_delete=models.CASCADE, verbose_name="Priority", null=True, blank=True)
    status = models.ForeignKey(Status, on_delete=models.CASCADE, verbose_name="Status", null=True, blank=True)
    reporter = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Reporter", null=True, blank=True)
    channel = models.ForeignKey(Channel, on_delete=models.CASCADE, verbose_name = "Channel")
    module = models.ForeignKey(Module, on_delete=models.CASCADE, verbose_name="Module")
    device_serial = models.ForeignKey(Device, on_delete=models.CASCADE, null=True, blank=True,verbose_name="Device Serial")

    description = models.TextField(verbose_name="Description")
    title = models.CharField(max_length=200, verbose_name="Title")
    jira_id = models.CharField(max_length=20, verbose_name="Jira Id", null=True, blank=True)
    assignee = models.ForeignKey(User, related_name="issue_assignee", on_delete=models.CASCADE, verbose_name= "assignee", null=True, blank=True)
    actor = models.ForeignKey(User, related_name="issue_actor", on_delete=models.CASCADE, verbose_name= "actor", null=True, blank=True)

    create_date= models.DateTimeField(verbose_name="Create Date", null=True, blank=True)
    update_date = models.DateTimeField(verbose_name="Last Update", null=True, blank=True)

    affects_version = models.FloatField(verbose_name="Affects Version", null=True, blank=True)
    fix_version = models.FloatField(verbose_name="Fix Version", null=True, blank=True)

    train_number = models.CharField(max_length=20, null=True, blank=True,  verbose_name="Train Number")
    train_from = models.CharField(max_length=20,  null=True, blank=True, verbose_name="Train From")
    train_to = models.CharField(max_length=20,  null=True, blank=True, verbose_name="Train To")
    trip_date = models.DateField(verbose_name="Trip Date", null=True, blank=True)

    teller = models.ForeignKey(EnrUser, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Teller")
    station = models.ForeignKey(Station, on_delete=models.CASCADE, null=True, blank=True, verbose_name="Station")
    comments = GenericRelation(Comment)

    subscription_type = models.CharField(max_length=50, null=True, blank=True, verbose_name="Subscription Type")
    subscription_number = models.IntegerField(null=True, blank=True, verbose_name="Subscription Number")
    subscription_expiry_date = models.DateField(null=True, blank=True, verbose_name="Subscription Expiry Date")

    teller_name = models.CharField(max_length=50, null=True, blank=True, verbose_name="Teller Name")
    teller_phone = models.CharField(max_length=15, null=True, blank=True, verbose_name="Teller phone")

    trans_number = models.CharField(max_length=10, null=True, blank=True, verbose_name="M#")


    def get_absolute_url(self):
        return reverse('ONSite:IssueUpdate', kwargs={'pk': self.id})
    

Core/forms.py
from django import forms

Core/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.shortcuts import  get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Issue, Status
from django_user_agents.utils import get_user_agent
from django.views.generic import ListView, UpdateView, CreateView, DetailView
from .models import Status, Module
from Auth.models import User
# Create your views here.


class Index(LoginRequiredMixin, ListView):
    login_url = '/auth/login'
    model = Issue
    paginate = 50
    template_name = 'Core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['status'] = Status.objects.all()
        context['module'] = Module.objects.all()
        return context


    def get_queryset(self):
        queryset = self.model.objects.filter(reporter=self.request.user).order_by('-id') | self.model.objects.filter(assignee=self.request.user).order_by('-id')
        if self.request.GET.get('issue_number'):
            queryset= self.model.objects.filter(id=self.request.GET.get('issue_number')).order_by('-id')
        if self.request.GET.get('title'):
            queryset= self.model.objects.filter(title__icontains=self.request.GET.get('title')).order_by('-id')
        if self.request.GET.get('date_from'):
            queryset = self.model.objects.filter(create_date__gte=self.request.GET.get('date_from')).order_by('-id')
        if self.request.GET.get('date_to'):
            queryset = self.model.objects.filter(create_date__lte=self.request.GET.get('date_to')).order_by('-id')
        if self.request.GET.get('module'):
            queryset = self.model.objects.filter(module__in=self.request.GET.get('module'))
        if self.request.GET.get('status'):
            queryset = self.model.objects.filter(status_id__in=self.request.GET.get('status'))


        def issue_weight():
            user_list = []
            queryset = User.objects.all()
            for i in queryset:
                user_list.append(i)

            print(user_list)
        issue_weight()
        return queryset

Core/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en"
      dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible"
              content="IE=edge">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>E-support</title>

        <!-- Prevent the demo from appearing in search engines -->
        <meta name="robots"
              content="noindex">

        <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7COswald:300,400,500,700%7CRoboto:400,500%7CExo+2:600&display=swap"
              rel="stylesheet">

        <!-- Perfect Scrollbar -->
        <link type="text/css"
              href="/static/huma/assets/vendor/perfect-scrollbar.css"
              rel="stylesheet">

        <!-- Material Design Icons -->
        <link type="text/css"
              href="/static/huma/assets/css/material-icons.css"
              rel="stylesheet">

        <!-- Font Awesome Icons -->
        <link type="text/css"
              href="/static/huma/assets/css/fontawesome.css"
              rel="stylesheet">

        <!-- Preloader -->
        <link type="text/css"
              href="/static/huma/assets/vendor/spinkit.css"
              rel="stylesheet">
        <link type="text/css"
              href="/static/huma/assets/css/preloader.css"
              rel="stylesheet">

        <!-- App CSS -->
        <link type="text/css"
              href="/static/huma/assets/css/app.css"
              rel="stylesheet">

        <!-- Dark Mode CSS (optional) -->
        <link type="text/css"
              href="/static/huma/assets/css/dark-mode.css"
              rel="stylesheet">

        <!-- Vector Maps -->
        <link type="text/css"
              href="/static/huma/assets/vendor/jqvmap/jqvmap.min.css"
              rel="stylesheet">

        <link href="/static/assets/select2/dist/css/select2.min.css" rel="stylesheet" />

    </head>

    <body class="layout-app layout-sticky-subnav ">



        <div class="mdk-drawer-layout js-mdk-drawer-layout"
             data-push
             data-responsive-width="992px">
            <div class="mdk-drawer-layout__content page-content">

                <!-- Header -->

                {% block Header %}
                    {% include "core/header.html" %}
                {% endblock %}
                <!-- // END Header -->

                {% block container %}

                {% endblock %}
            </div>


             <!-- sub modal -->
            <div class="modal fade" data-backdrop="static" id="sub_modal">
                <div class="modal-dialog modal-lg" id="sub_modal2">
                    <div class="modal-content" id="sub_body">
                            <span class="float-left">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </span>
                    </div>
                </div>
            </div>


        </div>



        <script>
             $(document).ready(function(){
                                                $('#delete_files').click(function(){
                                                    if(confirm("Are You Sure? ")){
                                                        var id = [];
                                                    $(':checkbox:checked').each(function(i){
                                                        id[i]=$(this).val()
                                                    })
                                                    if(id.length===0){
                                                        alert("please select files to delete?")
                                                    }else{
                                                        console.log(id);
                                                        $.ajax({
                                                            url: "{% url 'ONSite:DeleteFiles' %}",
                                                            method: "POST",
                                                            data:{
                                                                id,
                                                                csrfmiddlewaretoken: "{{ csrf_token }}",
                                                                dataType:"json"
                                                            },
                                                            success: function (response){
                                                                if(response.msg == 1){
                                                                     $("#files_div")
                                                                  .html("&nbsp;")
                                                                  .load(
                                                                    "{% url 'ONSite:FilesUpdateDive' object.id %}"
                                                                  );
                                                                }

                                                            },
                                                            failure: function (){
                                                                alert("check Files to delete")
                                                            }
                                                        })
                                                    }

                                                    }
                                                })
                                            })
        </script>

        <script>
            $(document).ready(function() {
                $('#issue_type').select2({width: '100%', placeholder:'Search...'});
                $('#device_serial').select2({width: '100%', placeholder:'Search...'});
                $('#module').select2({width: '100%', placeholder:'Search...'});
                $('#channel').select2({width: '100%', placeholder:'Search...'});
                $('#priority').select2({width: '100%', placeholder:'Search...'});
                $('#station').select2({width: '100%', placeholder:'Search...'});
            });
        </script>

        {% block script %}

        {% endblock script %}

        <!-- jQuery -->
        <script src="/static/huma/assets/vendor/jquery.min.js"></script>
        <script src="{% static 'assets/vendor/Zero.js' %}"></script>

        <!-- Bootstrap -->
        <script src="/static/huma/assets/vendor/popper.min.js"></script>
        <script src="/static/huma/assets/vendor/bootstrap.min.js"></script>

        <!-- Perfect Scrollbar -->
        <script src="/static/huma/assets/vendor/perfect-scrollbar.min.js"></script>

        <!-- DOM Factory -->
        <script src="/static/huma/assets/vendor/dom-factory.js"></script>

        <!-- MDK -->
        <script src="/static/huma/assets/vendor/material-design-kit.js"></script>

        <!-- App JS -->
        <script src="/static/huma/assets/js/app.js"></script>

        <!-- Highlight.js -->
        <script src="/static/huma/assets/js/hljs.js"></script>

        <!-- Global Settings -->
        <script src="/static/huma/assets/js/settings.js"></script>

        <!-- Flatpickr -->
        <script src="/static/huma/assets/vendor/flatpickr/flatpickr.min.js"></script>
        <script src="/static/huma/assets/js/flatpickr.js"></script>


        <!-- Tables -->
        <script src="/static/huma/assets/js/toggle-check-all.js"></script>
        <script src="/static/huma/assets/js/check-selected-row.js"></script>

        <!-- App Settings (safe to remove) -->
        <script src="/static/huma/assets/js/app-settings.js"></script>

        <script src="/static/assets/select2/dist/js/select2.min.js"></script>
    </body>

</html>

Core/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en"
      dir="ltr">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible"
              content="IE=edge">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>E-support</title>

        <!-- Prevent the demo from appearing in search engines -->
        <meta name="robots"
              content="noindex">

        <link href="https://fonts.googleapis.com/css?family=Lato:400,700%7COswald:300,400,500,700%7CRoboto:400,500%7CExo+2:600&display=swap"
              rel="stylesheet">

        <!-- Perfect Scrollbar -->
        <link type="text/css"
              href="/static/huma/assets/vendor/perfect-scrollbar.css"
              rel="stylesheet">

        <!-- Material Design Icons -->
        <link type="text/css"
              href="/static/huma/assets/css/material-icons.css"
              rel="stylesheet">

        <!-- Font Awesome Icons -->
        <link type="text/css"
              href="/static/huma/assets/css/fontawesome.css"
              rel="stylesheet">

        <!-- Preloader -->
        <link type="text/css"
              href="/static/huma/assets/vendor/spinkit.css"
              rel="stylesheet">
        <link type="text/css"
              href="/static/huma/assets/css/preloader.css"
              rel="stylesheet">

        <!-- App CSS -->
        <link type="text/css"
              href="/static/huma/assets/css/app.css"
              rel="stylesheet">

        <!-- Dark Mode CSS (optional) -->
        <link type="text/css"
              href="/static/huma/assets/css/dark-mode.css"
              rel="stylesheet">

        <!-- Vector Maps -->
        <link type="text/css"
              href="/static/huma/assets/vendor/jqvmap/jqvmap.min.css"
              rel="stylesheet">

{#        <link href="/static/assets/select2/dist/css/select2.min.css" rel="stylesheet" />#}

        <!--Huma select2  -->
        <link type="text/css"
              href="/static/huma/assets/vendor/select2/select2.min.css"
              rel="stylesheet">
        <link type="text/css"
              href="/static/huma/assets/css/select2.css"
              rel="stylesheet">
        <style>
        .modalPersonResp{
        height:80%;
        width: 50%;

        overflow: scroll;
     }

    </style>
    </head>

    <body class="layout-app layout-sticky-subnav ">



        <div class="mdk-drawer-layout js-mdk-drawer-layout"
             data-push
             data-responsive-width="992px">
            <div class="mdk-drawer-layout__content page-content">

                <!-- Header -->

                {% include "core/header.html" %}

                <!-- // END Header -->



             <!-- end open and close buttons -->


                <div class="container-fluid page__container">
                    <div class="page-section">
                      <!-- message div -->
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                                <i class="mdi mdi-check-all mr-2"></i>
                               <h2> {{ message|safe }} </h2>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">×</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}

                    {% include 'core/filter.html' %}

                    <div class=" mb-lg-18pt">
                        <div class="container-fluid page__container page__container page-section">
                             <div class="page-separator">
                        <div class="page-separator__text">
                                <ol class="breadcrumb p-0 m-0">
                                    <li class="breadcrumb-item"><a href="{% url 'Core:Index' %}">Home</a></li>
                                    <li class="breadcrumb-item active">
                                        My Issues
                                    </li>
                                </ol>
                        </div>
                    </div>
                            {% block issue_div %}

                            {% endblock %}

                        </div>
                    </div>

                    </div>
                </div>
            </div>
            <!-- // END drawer-layout__content -->



             <!-- sub modal -->
            <div class="modal fade " data-backdrop="static" id="sub_modal">
                <div class="modal-dialog modal-xl" id="sub_modal2"  >
                    <div class="modal-content" id="sub_body" >
                            <span class="float-left">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            </span>
                    </div>
                </div>
            </div>


        </div>



        {% block script %}

        {% endblock script %}


        <!-- jQuery -->
        <script src="/static/huma/assets/vendor/jquery.min.js"></script>
        <script src="/static/assets/vendor/Zero.js"></script>

        <!-- Bootstrap -->
        <script src="/static/huma/assets/vendor/popper.min.js"></script>
        <script src="/static/huma/assets/vendor/bootstrap.min.js"></script>

        <!-- Perfect Scrollbar -->
        <script src="/static/huma/assets/vendor/perfect-scrollbar.min.js"></script>

        <!-- DOM Factory -->
        <script src="/static/huma/assets/vendor/dom-factory.js"></script>

        <!-- MDK -->
        <script src="/static/huma/assets/vendor/material-design-kit.js"></script>

        <!-- App JS -->
        <script src="/static/huma/assets/js/app.js"></script>

        <!-- Highlight.js -->
        <script src="/static/huma/assets/js/hljs.js"></script>

        <!-- Global Settings -->
        <script src="/static/huma/assets/js/settings.js"></script>

        <!-- Flatpickr -->
        <script src="/static/huma/assets/vendor/flatpickr/flatpickr.min.js"></script>
        <script src="/static/huma/assets/js/flatpickr.js"></script>


        <!-- Tables -->
        <script src="/static/huma/assets/js/toggle-check-all.js"></script>
        <script src="/static/huma/assets/js/check-selected-row.js"></script>

        <!-- App Settings (safe to remove) -->
        <script src="/static/huma/assets/js/app-settings.js"></script>

{#        <script src="/static/assets/select2/dist/js/select2.min.js"></script>#}
        <script src="/static/huma/assets/vendor/select2/select2.min.js"></script>
        <script src="/static/huma/assets/js/select2.js"></script>
    </body>

</html>